# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hacienda < Formula
  desc "🇨🇷 Hacienda es una aplicación que se conecta al API del Ministerio de Hacienda de Costa Rica."
  homepage "https://kevinah95.github.io/hacienda"
  version "0.10.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.0/hacienda_Darwin_arm64.tar.gz"
      sha256 "9b3846cdc5ea3d0239a97fd5b65ca868b436198e5ab3f5951dd7790c81d89ea8"

      def install
        bin.install "hacienda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.0/hacienda_Darwin_x86_64.tar.gz"
      sha256 "de03ea2a519960d608adfea64f53d48a3495c029565c3bae0ea5be44d48256c2"

      def install
        bin.install "hacienda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.0/hacienda_Linux_arm64.tar.gz"
      sha256 "c5e176ef6a574a8b7dfab19ede8daed74df28bf0d1b33fef789a0bca993a83aa"

      def install
        bin.install "hacienda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.0/hacienda_Linux_x86_64.tar.gz"
      sha256 "cf12dcf8f366e3bf40688d859157cb6f819e76db70fc90d95cff3e21aa3a4f8d"

      def install
        bin.install "hacienda"
      end
    end
  end

  test do
    system "#{bin}/hacienda -v"
  end
end
